
execute_unload 'gdx/00_results.gdx'
r_CostTotal,
r_CostTransport,
r_CostTransportNational,
r_CostTransportInternational,
r_CostTransportConversion,
r_CostProduction,
r_CostTotalDummy,
r_Path,
r_ProductionNode,
r_ProductionH2System,
r_ProductionDummy,
r_H2_system,
r_Supply,
r_Supply_TotalCostProduction,
r_Supply_TotalCostTransportNational,
r_Supply_TotalCostTransportInternational,
r_Supply_TotalCostTransportConversion,
r_Supply_CostProduction,
r_Supply_CostTransportNational,
r_Supply_CostTransportInternational,
r_Supply_CostTransportConversion
;